name: Test cron

# on:
#   schedule:
#     - cron: '*/5 * * * *'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
           
        - name: auten
          run: |
            curl --request GET \
            --url "https://api.github.com/octocat" \
            --header "Authorization: Bearer $GH_TOKEN" \

        - name: list repo
          run: |    
            curl \
            -H "Accept: application/vnd.github+json" \ 
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/users/cadu1982/repos


        # curl \
          # -X PATCH \
          # -H "Accept: application/vnd.github+json" \ 
          # -H "Authorization: Bearer $GH_TOKEN" \
          # https://api.github.com/repos/cadu1982/cron-api \
          # -d '{"name":"Hello-World","description":"This is your first repository","homepage":"https://github.com","private":true,"has_issues":true,"has_projects":true,"has_wiki":true}'

        # curl \
          # -H "Accept: application/vnd.github+json" \ 
          # -H "Authorization: Bearer $GH_TOKEN" \
          # https://api.github.com/repos/cadu1982/cron-api/actions/permissions
          
        

        # curl --request GET \
          # --url "https://api.github.com/octocat" \
          # --header "Authorization: Bearer $GH_TOKEN"