name: Test cron

# on:
#   schedule:
#     - cron: '*/5 * * * *'

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/repos/cadu1982/cron-api/actions/permissions
          
        # # curl \
          # -H "Accept: application/vnd.github+json" \ 
          # -H "Authorization: Bearer $GH_TOKEN " \
          # https://api.github.com/repos/cadu1982/cron-api/environments/prod/deployment-branch-policies/master
         # gh api \
          # -H "Accept: application/vnd.github+json" \
          #  /repos/cadu1982/*/environments/*/deployment-branch-policies

        # curl --request GET \
          # --url "https://api.github.com/octocat" \
          # --header "Authorization: Bearer $GH_TOKEN"