name: Test cron

# on:
#   schedule:
#     - cron: '*/5 * * * *'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
           
        # - name: install json
        #   run: |
        #     sudo apt-get update
        #     sudo apt-get install jsonnet

        - name: list repo
          run: |    
            curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/users/cadu1982/repos" | awk '/"name"/ {print $2}' | sed -e 's/\"//g' | sed -e 's/\,//g'

        # - name: Politica branch
        #   run: |
        #      curl -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/repos/cadu1982/testando/branches/master/protection -d '{"required_status_checks":{"strict":true,"contexts":["continuous-integration/travis-ci"]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":["octocat"],"teams":["justice-league"]},"dismiss_stale_reviews":false,"require_code_owner_reviews":true,"required_approving_review_count":2,"bypass_pull_request_allowances":{"users":["octocat"],"teams":["justice-league"]}},"restrictions":{"users":["octocat"],"teams":["justice-league"],"apps":["super-ci"]},"required_linear_history":false,"allow_force_pushes":false,"allow_deletions":false,"block_creations":false,"required_conversation_resolution":false}'

        # - name: teste 3
        #   run: |
        #     curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/repos/cadu1982/deploy/branches/master/protection/required_pull_request_reviews
        # 